version: '3.8'

services:
  # php service
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: php
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app_network

  # nginx service - PORT 80
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app_network

  # mysql service
  db:
    image: mariadb:latest
    container_name: db
    ports:
      - "1306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_volume:/var/lib/mysql/
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_volume:
    driver: local